fix scanner split infinite loop cause by extftool error output
barasher/go-exiftool pull request #46
Opened 2021-07-27 15:51 UTC by switch-li

if exiftool parse file error, maybe return unknow string (This is usually caused by exifTool error output).
e.g.
filehash: 8e2a7aaeeee829f77b1a1029b9f7524879bbe399
outpuut: 'x' outside of string in unpack at /usr/share/perl5/vendor_perl/Image/ExifTool.pm line 5059.

2021-07-27 15:55 UTC, switch-li commented
exiftool output not always return string split by "{ready}\n"
lot of times return a error message split by "\n"

2021-07-27 21:44 UTC, barasher commented
Hi, thanks for the PR.
Could you please add some unit tests ?

2021-07-27 21:52 UTC, barasher requested changes
Could you please share a file that `go-exiftool` does not handle well ?

2021-07-27 21:52 UTC, barasher commented on exiftool.go
> -	case <- ch:
This code doesn't seem to respect golang coding style. Could you please run gofmt?

2021-07-27 21:52 UTC, barasher commented on exiftool.go
> +	if i := bytes.IndexByte(data, '\n'); i >= 0 {
Should be unit-tested

2021-07-27 21:52 UTC, barasher commented on exiftool.go
> +			return i + 1, data[0:i], nil
What are `[]byte{91, 123}` ? It's not really clear

2021-08-18 21:09 UTC, barasher commented
@switch-li, could you please have a look at my questions ?

2021-08-25 16:32 UTC, closed without merging